select
    PRODUCT_ID
    , MAX(CASE WHEN ATTRIBUTE_NAME = 'DIVISION' THEN ATTRIBUTE_VALUE END) AS DIVISION
    , MAX(CASE WHEN ATTRIBUTE_NAME = 'CATEGORY' THEN ATTRIBUTE_VALUE END) AS CATEGORY
    , MAX(CASE WHEN ATTRIBUTE_NAME = 'SUBCATEGORY' THEN ATTRIBUTE_VALUE END) AS SUBCATEGORY
from
    {{ ref('stg_pdm__product_attributes') }}
where
    ATTRIBUTE_NAME in ('DIVISION', 'CATEGORY', 'SUBCATEGORY')
group by
    PRODUCT_ID
HAVING
    MAX(CASE WHEN ATTRIBUTE_NAME = 'DIVISION' THEN ATTRIBUTE_VALUE END) IS NOT NULL