select
    PRODUCTSETID as PRODUCT_SET_ID
    , AVERAGERATING as REVIEW_AVERAGE
    , REVIEWCOUNT as REVIEW_COUNT
    , STATUS as STATUS
    , date(DATECREATED) as CREATED_AT
    , date(DATECHANGED) as UPDATED_AT
    , SITEID as SITE_ID
from
    {{source('FBB_PRODUCTS', 'TURNTO_PRODUCTSETREVIEWS')}}
