select
    SFCC_PRODUCT_ID
     , VIEWS
     , UNITS
     , ORDERS
     , REVENUE
     , ORDERDISCOUNT AS ORDER_DISCOUNT
     , PRODUCTDISCOUNT AS PRODUCT_DISCOUNT
     , SITEID AS SITE_ID
     , date(DATECREATED) AS CREATED_AT
from
    {{source('FBB_PRODUCTS', 'OMNITURE_DATA')}}
