select
    CLASSIFICATIONID as CLASSIFICATION_ID
    , PARENTCLASSIFICATIONID as PARENT_CLASSIFICATION_ID
    , NAME as NAME
    , to_boolean(CANHAVEPRODUCTS) as CAN_HAVE_PRODUCTS
    , GROUPID as GROUP_ID
    , date(DATECREATED) as CREATED_AT
    , date(DATECHANGED) as UPDATED_AT
from
    {{ source('FBB_PRODUCTS', 'CLASSIFICATION') }}
