select
    IMAGEID as IMAGE_ID
    , BRANDID as BRAND_ID
    , MFDEPTID as MF_DEPARTMENT_ID
    , MFITEMID as MF_ITEM_ID
    , MFSTYLENO as MF_STYLE_ID
    , nullif(replace(SEQUENCE, chr(0), ''), '') as SEQUENCE
    , IMAGENAME as IMAGE_NAME
    , IMAGETYPEID as IMAGE_TYPE_ID
    , IMAGECODE as IMAGE_CODE
    , FILENAME as FILE_NAME
    , VENDORID as VENDOR_ID
    , IMAGEURL as IMAGE_URL
    , SFCC_URL as SFCC_URL
    , STATUS as STATUS
    , date(DATECREATED) as CREATED_AT
    , date(DATECHANGED) as UPDATED_AT
    , date(DATELOCALDOWNLOAD) as DATE_DOWNLOAD
    , date(DATEWEBDAVUPLOAD) as DATE_WEB_DAV_UPLOAD
    , MODIFIEDBY as MODIFIED_BY
from
    {{source('FBB_PRODUCTS', 'IMAGE')}}