select
    COLORIMAGEID as COLOR_IMAGE_ID
    , COLORID as COLOR_ID
    , IMAGEID as IMAGE_ID
    , IMAGETYPEID as IMAGE_TYPE_ID
    , STATUS as STATUS
    , try_to_number(RETRYCOUNT) as RETRY_COUNT
    , date(DATECREATED) as CREATED_AT
    , date(DATECHANGED) as UPDATED_AT
    , date(DATEPUBLISHED) as DATE_PUBLISHED
    , MODIFIEDBY as MODIFIED_BY
from
    {{source('FBB_PRODUCTS', 'COLORIMAGE')}}