select
    trim(ATTRIBUTEVALUEID) as ATTRIBUTE_VALUE_ID
    , trim(ATTRIBUTEID) as ATTRIBUTE_ID
    , trim(ATTRIBUTEVALUE) as ATTRIBUTE_VALUE
    , trim(DISPLAYVALUE) as DISPLAY_VALUE
    , STATUS as STATUS
    , date(DATECREATED) as CREATED_AT
    , date(DATECHANGED) as UPDATED_AT
from
    {{ source('FBB_PRODUCTS', 'ATTRIBUTEVALUE') }}
