select
    GROUPID as GROUP_ID
    , MFDISPLAYSIZE as MF_DISPLAY_SIZE
    , BRDISPLAYSIZE as BR_DISPLAY_SIZE
    , date(DATECREATED) as CREATED_AT
from
    {{ source('FBB_PRODUCTS', 'BR_SIZECONVERSION') }}
