select
	to_varchar(GIFTCARDSTYLEID) as GIFT_CARD_STYLE_ID
	, to_varchar(GIFTCARDID) as GIFT_CARD_ID
	, to_varchar(MFSTYLEID) as MF_STYLE_ID
	, COLOR
	, IMAGE
	, STATUS
    , date(DATECREATED) as CREATED_AT
    , date(DATECHANGED) as UPDATED_AT
	, MODIFIEDBY as MODIFIED_BY
from
    {{source('FBB_GIFT_CARDS', 'GIFTCARDSTYLE')}}