select
    SIZEID as SIZE_ID
    , QUANTITY as QUANTITY
    , BACKORDERQUANTITY as BACKORDER_QUANTITY
    , STATUS as STATUS
    , QUANTITYUNAVAILABLEAMAZON as QUANTITY_UNAVAILABLE_AMAZON
    , RETRYCOUNT as RETRY_COUNT
    , date(DATECREATED) as CREATED_AT
    , date(DATECHANGED) as UPDATED_AT
    , date(asOFDATE) as AS_OF_DATE
    , date(NEXTAVAILABLEDATE) as NEXT_AVAILABLE_DATE
    , date(DATEPUBLISHED) as  PUBLISHED_AT
from
  {{source('MP_PRODUCTS', 'MP_INVENTORY')}}