select
    PRODUCTID as PRODUCT_ID
    , ATTRIBUTEID as ATTRIBUTE_ID
    , trim(ATTRIBUTENAME) as ATTRIBUTE_NAME
    , ATTRIBUTEVALUEID as ATRIBUTE_VALUE_ID
    , trim(ATTRIBUTEVALUE) as ATTRIBUTE_VALUE
    , date(DATECREATED) as CREATED_AT
    , date(DATECHANGED) as UPDATED_AT
    , STATUS as STATUS
from
    {{ source('MP_PRODUCTS', 'MP_PRODUCTATTRIBUTEVALUE') }}
