select
    COLORIMAGEID as COLOR_IMAGE_ID
    , COLORID AS COLOR_ID
    , IMAGEID AS IMAGE_ID
    , IMAGETYPEID AS IMAGE_TYPE_ID
    , STATUS AS STATUS
    , date(DATECREATED) as CREATED_AT
    , date(DATECHANGED) as UPDATED_AT
    , date(DATEPUBLISHED) AS DATE_PUBLISHED
    , MODIFIEDBY AS MODIFIED_BY
    , RETRYCOUNT AS RETRY_COUNT
from
    {{source('MP_PRODUCTS', 'MP_COLORIMAGE')}}