select
    PRODUCTIMAGEID as PRODUCT_IMAGE_ID
    , PRODUCTID as PRODUCT_ID
    , IMAGEID as IMAGE_ID
    , IMAGETYPEID as IMAGE_TYPE_ID
    , STATUS as STATUS
    , date(DATECREATED) as CREATED_AT
    , date(DATECHANGED) as UPDATED_AT
    , MODIFIEDBY as MODIFIED_BY
    , date(DATEPUBLISHED) as PUBLISHED_AT
    , RETRYCOUNT as RETRY_COUNT
from
    {{source('MP_PRODUCTS', 'MP_PRODUCTIMAGE')}}
