select
    PRODUCTIMAGEID as PRODUCT_IMAGE_ID
    , PRODUCTID as PRODUCT_ID
    , IMAGEID as IMAGE_ID
    , IMAGETYPEID as IMAGE_TYPE_ID
    , STATUS as STATUS
    , date(DATECREATED) as CREATED_AT
    , date(DATECHANGED) as UPDATED_AT
    , date(PCMDATECHANGED) as PCM_UPDATED_AT
    , MODIFIEDBY as MODIFIED_BY
    , date(STARTTIME) as START_TIME
    , date(ENDTIME) as END_TIME
from
    {{source('FBB_PRODUCTS', 'PRODUCTIMAGE')}}