select
    SIZEID as SIZE_ID
    , QUANTITY as QUANTITY
    , BACKORDERQUANTITY as BACKORDER_QUANTITY
    , QUANTITYUNAVAILABLEAMAZON QUANTITY_UNAVAILABLE_AMAZON
    , STATUS as STATUS
    , date(ASOFDATE) as ASOF_DATE
    , date(NEXTAVAILABLEDATE) as NEXT_AVAILABLE_DATE
    , date(DATECREATED) as CREATED_AT
    , date(DATECHANGED) as UPDATED_AT
from
    {{source('FBB_PRODUCTS', 'INVENTORY')}}