select
    PRODUCTID AS PRODUCT_ID
     , ATTRIBUTEID AS ATTRIBUTE_ID
     , ATTRIBUTENAME AS ATTRIBUTE_NAME
     , ATTRIBUTEVALUEID AS ATTRIBUTE_VALUE_ID
     , ATTRIBUTEVALUE AS ATTRIBUTE_VALUE
     , date(DATECREATED) AS CREATED_AT
     , date(DATECHANGED) AS UPDATED_AT
     , STATUS as STATUS
from
    {{source('FBB_PRODUCTS', 'PRODUCTATTRIBUTEVALUE')}}
