select
    SIZEID AS SIZE_ID
    , trim(BRAND) AS BRAND
    , nullif(replace(trim(CALLOUTMESSAGE), chr(0), ''), '') as CALLOUT_MESSAGE
    , nullif(replace(trim(COUPONCODE), chr(0), ''), '') as COUPON_CODE
    , FINALPRICE AS FINAL_PRICE
    , USDPRICE AS USD_PRICE
    , USDFINALPRICE AS USD_FINAL_PRICE
    , AUDPRICE AUD_PRICE
    , AUDFINALPRICE AS AUD_FINAL_PRICE
    , CADPRICE AS CAD_PRICE
    , CADFINALPRICE AS CAD_FINAL_PRICE
    , MXNPRICE AS MXN_PRICE
    , MXNFINALPRICE AS MXN_FINAL_PRICE
    , date(DATECREATED) AS CREATED_AT
from
    {{source('FBB_PRODUCTS', 'SFRA_FINALPRICE')}}
