select
    SFCC_PRODUCT_ID
    , PRODUCTID as PRODUCT_ID
    , STYLEID as STYLE_ID
    , SIZEID as SIZE_ID
    , COLOR as COLOR
    , SKUID as SKU_ID
    , SFCC_SIZEID as SFCC_SIZE_ID
    , LISTPRICE as LIST_PRICE
    , SALEPRICE as SALE_PRICE
    , CLEARANCEINDICATOR as CLEARANCE_INDICATOR
    , to_boolean(ISFINALSALE) as IS_FINAL_SALE
    , INVENTORY as INVENTORY_QUANTITY
    , BACKORDER as BACKORDER_QUANTITY
    , SITEID as SITE_ID
    , date(DATECREATED) as CREATED_AT
from
    {{ source('FBB_PRODUCTS', 'SFRA_SIZE') }}
