select
    BRANDID as BRAND_ID
    , BRANDCODE as BRAND_CODE
    , BRANDNAME as BRAND_NAME
    , PCMENABLED as PCM_ENABLED
    , SFCCENABLED as SFCC_ENABLED
    , MILENNAIMAGEURL as MILENNA_IMAGE_URL
    , SFCCSITEID as SFCC_SITE_ID
    , SFCCMASTERCATALOG as SFCC_MASTER_CATALOG
    , SFCCSITEURL as SFCC_SITE_URL
    , SFCCSITECATALOG as SFCC_SITE_CATALOG
    , SFCCDEFAULTCLEARANCECATEGORY as SFCC_DEFAULT_CLEARANCE_CATEGORY
    , SFCCDEFAULTFINALSALECATEGORY as SFCC_DEFAULT_FINAL_SALE_CATEGORY
    , SFCCCATEGORYCODE as SFCC_CATEGORY_CODE
    , IMAGEDOMAIN as IMAGE_DOMAIN
    , BLOOMREACHBRANDNAME as BLOOMREACH_BRAND_NAME
from
    {{source('FBB_PRODUCTS', 'BRAND')}}
