select
    PRODUCTID AS PRODUCT_ID
    , trim(COLORID) AS COLOR_ID
    , TOTALSALES AS TOTAL_SALES
    , trim(COLOR) AS COLOR
    , COLORSORTORDER AS COLOR_SORT_ORDER
    , date(DATECHANGED) AS UPDATED_AT
from
    {{source('FBB_PRODUCTS', 'COLORSORTORDERSKU')}}
