select
    SFCC_PRODUCT_ID as SFCC_PRODUCT_ID
    , VARIATION_VALUE as VARIATION_VALUE
    , TYPE as TYPE
    , URL as URL
    , RELATIVEURL as RELATIVE_URL
    , IMAGE_NAME as IMAGE_NAME
    , date(DATECREATED) as CREATED_AT
    , PRODUCTID as PRODUCT_ID
from
    {{ source('FBB_PRODUCTS', 'SFRA_IMAGEURL') }}
