select
    PRICEID as PRICE_ID
    , SIZEID as SIZE_ID
    , MEDIAKEY as MEDIA_KEY
    , BRANDID as BRAND_ID
    , try_to_decimal(SELLINGPRICE, 30, 4) as SELLING_PRICE
    , STATUS as STATUS
    , date(SELLINGPRICESTARTDATE) as SELLING_PRICE_START_DATE
    , date(SELLINGPRICEENDDATE) as SELLING_PRICE_END_DATE
    , date(DATECREATED) as CREATED_AT
    , date(DATECHANGED) as UPDATED_AT
    , date(MFDATECHANGED) as MF_UPDATED_AT
    , date(STARTTIME) as START_TIME
    , date(ENDTIME) as END_TIME
    , MODIFIEDBY as MODIFIED_BY

from
    {{source('FBB_PRODUCTS', 'PRICE')}}