select
    ITEM_NUMBER
    , SEASON
    , SEASON_CD
    , SEASON_YEAR
    , DIVISION
    , DEPT
    , DIVISION_DEPT
    , DESCRIPTION_SHORT
    , DESCRIPTION_FULL
    , BUYER_NUMR
    , CTL_BUYER_NUMR
    , CARE_CODE
    , MASTER_ITEM_NUMBER
    , MKTG_CAT
    , TALL_ITEM_SW
    , NEW_REPEAT_SW
    , CORE_ITEM_SW
    , FASHION_TYPE
    , SEAS_OR_PERENNIAL
    , NATIONAL_BRAND
    , FIBER_CODE_1
    , FIBER_DESC_1
    , FIBER_CODE_2
    , FIBER_DESC_2
    , VENDOR_NUMBER
    , ITEM_SOURCE
    , COUNTRY_OF_ORIGIN
    , MODULE_TYPE
    , BRAND_LABEL
from
    {{source('CMN', 'CMN_ITEM_SEASON')}}
